Repository pingcap/dumpling, pull requests merged in 2020-03, with the labels that each got.

#36 Add a simple README file.
  README.md
Labels: status/LGT1

#37 tests: some improvements to the integration tests
  .travis.yml
  go.sum
  tests/_utils/run_sql
  tests/_utils/run_sql_file
  tests/file_size/run.sh
  tests/naughty_strings/data/naughty_strings-schema-create.sql
  tests/naughty_strings/data/naughty_strings.t-schema.sql
  tests/naughty_strings/data/naughty_strings.t.sql
  tests/naughty_strings/run.sh
  tests/primary_key/result/pk_case_0.sql
  tests/primary_key/result/pk_case_1.sql
  tests/primary_key/result/pk_case_2.sql
  tests/primary_key/result/pk_case_3.sql
  tests/run.sh
  tests/views/data/views-schema-create.sql
  tests/views/run.sh
  v4/export/dump_test.go
  v4/export/sql.go
Labels: status/LGT1

#39 support `--statement-size` in dumpling
  cmd/dumpling/main.go
  v4/export/config.go
  v4/export/ir.go
  v4/export/ir_impl.go
  v4/export/ir_impl_test.go
  v4/export/writer.go
  v4/export/writer_test.go
  v4/export/writer_util.go
Labels: status/PTAL

#34 tests: add e2e test
  .gitignore
  .travis.yml
  fix.sql
  install.sh
  tests/_utils/check_sync_diff
  tests/_utils/run_lightning
  tests/_utils/run_services
  tests/e2e/conf/diff_config.toml
  tests/e2e/conf/lightning.toml
  tests/e2e/run.sh
  tests/file_size/run.sh
  tests/run.sh
  tests/views/run.sh
Labels: status/LGT1

#45 Output metadata after the dump operation
  v4/export/dump.go
  v4/export/metadata.go
  v4/export/metadata_test.go
Labels: status/PTAL

#40 Support --rows and --where clause
  cmd/dumpling/main.go
  tests/naughty_strings/run.sh
  tests/primary_key/run.sh
  tests/rows/conf/diff_config.toml
  tests/rows/conf/lightning.toml
  tests/rows/run.sh
  v4/export/config.go
  v4/export/dump.go
  v4/export/dump_test.go
  v4/export/ir.go
  v4/export/ir_impl.go
  v4/export/ir_impl_test.go
  v4/export/prepare.go
  v4/export/sql.go
  v4/export/sql_test.go
  v4/export/test_util.go
  v4/export/writer.go
  v4/export/writer_test.go
Labels: status/LGT1, status/PTAL

#47 ignore generated column
  tests/ignore_generate_column/conf/diff_config.toml
  tests/ignore_generate_column/conf/lightning.toml
  tests/ignore_generate_column/run.sh
  v4/export/dump.go
  v4/export/dump_test.go
  v4/export/ir.go
  v4/export/ir_impl.go
  v4/export/sql.go
  v4/export/sql_test.go
  v4/export/test_util.go
  v4/export/writer_util.go
Labels: status/LGT1

#49 Add enable backslash
  cmd/dumpling/main.go
  go.mod
  go.sum
  tests/naughty_strings/data/naughty_strings.escape-schema.sql
  tests/naughty_strings/data/naughty_strings.escape.sql
  tests/naughty_strings/expect/naughty_strings.escape.sql
  tests/naughty_strings/expect/naughty_strings.t.sql
  tests/naughty_strings/naughty_strings.escape-schema.sql
  tests/naughty_strings/run.sh
  v4/export/config.go
  v4/export/ir.go
  v4/export/ir_impl.go
  v4/export/sql.go
  v4/export/sql_type.go
  v4/export/sql_type_test.go
  v4/export/test_util.go
  v4/export/writer_util.go
Labels: status/PTAL

#51 add SetLogger to support combine log with DM
  cmd/dumpling/main.go
  v4/export/config.go
  v4/export/dump.go
  v4/export/prepare.go
  v4/log/log.go
Labels: status/PTAL

#50 optimize dumpling's effiency
  tests/primary_key/result/pk_case_0.sql
  tests/primary_key/result/pk_case_1.sql
  tests/primary_key/result/pk_case_2.sql
  tests/primary_key/result/pk_case_3.sql
  v4/export/dump_test.go
  v4/export/ir.go
  v4/export/ir_impl.go
  v4/export/ir_impl_test.go
  v4/export/sql_type.go
  v4/export/sql_type_test.go
  v4/export/writer.go
  v4/export/writer_test.go
  v4/export/writer_util.go
  v4/export/writer_util_test.go
Labels: status/PTAL

#53 optimize dumpling's effiency hotfix
  v4/export/writer_util.go
Labels: status/PTAL
