Repository pingcap/dumpling, pull requests merged in 2021-02, with the labels that each got.

#237 dependency: update br dependency to update external file usage
  go.mod
  go.sum
  v4/export/writer_util.go
Labels: status/LGT1

#239 gcs: fix dumpling bug
  v4/export/config.go
  v4/export/dump.go
  v4/export/writer.go
  v4/export/writer_util.go
Labels: severity/moderate, status/LGT1, status/PTAL, type/bug

#240 .github: switch from Travis CI to GitHub Actions
  .github/workflows/go.yml
  .travis.yml
  README.md
  install.sh
  tests/quote/data/quote-database-schema-create.sql
  tests/quote/data/quote-database.quote-table-schema.sql
  tests/rows/run.sh
  tests/s3/run.sh
  tests/views/run.sh
  v4/export/config.go
Labels: status/PTAL
