Repository pingcap/dumpling, pull requests merged in 2021-07, with the labels that each got.

#290 export: don't +1 TSO when set GC safepoint
  v4/export/sql.go
  v4/export/sql_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, status/LGT1, status/can-merge

#301 dump: always split TiDB v3.* tables through tidb rowid to save TiDB's memory
  go.mod
  v4/export/config.go
  v4/export/dump.go
  v4/export/prepare.go
  v4/export/region_results.csv
  v4/export/sql.go
  v4/export/sql_test.go
  v4/export/writer_util_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XXL, status/LGT1, status/PTAL, status/can-merge

#305 *: reduce dumpling accessing database and information_schema usage to improve its stability
  Makefile
  go.mod
  go.sum
  tests/run.sh
  tests/views/run.sh
  v4/export/block_allow_list.go
  v4/export/block_allow_list_test.go
  v4/export/consistency.go
  v4/export/consistency_test.go
  v4/export/dump.go
  v4/export/dump_test.go
  v4/export/ir.go
  v4/export/ir_impl.go
  v4/export/metrics.go
  v4/export/prepare.go
  v4/export/prepare_test.go
  v4/export/sql.go
  v4/export/sql_test.go
  v4/export/status.go
  v4/export/test_util.go
  v4/export/util.go
  v4/export/writer_util.go
  v4/export/writer_util_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XXL, status/LGT1, status/PTAL, status/can-merge

#319 security: support init tls config from cert/key/ca bytes
  go.mod
  go.sum
  v4/export/config.go
Labels: size/M, status/LGT1, status/can-merge

#320 config: do not show ssl bytes
  v4/export/config.go
Labels: size/XS, status/LGT1, status/can-merge
