Repository pingcap/dumpling, pull requests merged in 2021-03, with the labels that each got.

#250 export: ignore unused parameters
  v4/export/test_util.go
Labels: size/XS, status/LGT1, status/can-merge

#254 add estimate total rows count to metrics for dump table
  v4/export/dump.go
  v4/export/metrics.go
  v4/export/sql.go
  v4/export/status.go
Labels: size/M, status/LGT1, status/can-merge

#246 *: add logs and try fixing error log
  .github/workflows/go.yml
  Makefile
  v4/export/dump.go
  v4/export/ir.go
  v4/export/ir_impl.go
  v4/export/test_util.go
  v4/export/writer.go
  v4/export/writer_util.go
  v4/export/writer_util_test.go
Labels: size/L, status/LGT1, status/PTAL, status/can-merge

#256 dump: fix the problem that dumpling gets stuck after the database connection is lost
  v4/export/config.go
  v4/export/dump.go
  v4/export/dump_test.go
Labels: needs-cherry-pick-5.0, severity/moderate, size/L, status/LGT1, status/PTAL, status/can-merge, type/bug

#260 dump: support new where sql generator
  v4/export/dump.go
  v4/export/sql.go
  v4/export/sql_test.go
  v4/export/sql_type.go
Labels: size/XL, status/LGT1, status/PTAL, status/can-merge
