Repository pingcap/dumpling, pull requests merged in 2021-08, with the labels that each got.

#311 export: initial work to support MemSQL/SingleStore
  .gitignore
  v4/export/sql.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/S, status/LGT1, status/can-merge

#325 *: use `show full tables` in ListAllDatabasesTables
  .github/workflows/go.yml
  Makefile
  tests/quote/data/quote-database-schema-create-mysql57.sql
  tests/quote/data/quote-database.quote-table-schema-mysql57.sql
  tests/quote/data/quote-database.quote-table.000000000-mysql57.sql
  tests/quote/run.sh
  tests/run.sh
  tests/views/run.sh
  v4/export/config.go
  v4/export/config_test.go
  v4/export/dump.go
  v4/export/dump_test.go
  v4/export/prepare_test.go
  v4/export/sql.go
Labels: status/LGT1, status/can-merge, needs-cherry-pick-release-5.0, size/XL, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.1

#324 prepare: filter databases before show table status
  v4/export/block_allow_list.go
  v4/export/block_allow_list_test.go
  v4/export/dump.go
  v4/export/prepare.go
  v4/export/prepare_test.go
Labels: status/LGT1, status/can-merge, size/M, needs-cherry-pick-release-5.0, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.1

#335 *: update dumpling log and pd usage
  v4/export/dump.go
  v4/export/http_handler.go
  v4/export/sql.go
  v4/export/writer_util.go
  v4/log/log.go
Labels: status/LGT1, status/can-merge, size/M, needs-cherry-pick-release-5.0, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.1
