Repository pingcap/dumpling, pull requests merged in 2021-11, with the labels that each got.

#380 tests: fix sync_diff configs for CI
  tests/all_generate_column/conf/diff_config.toml
  tests/e2e/conf/diff_config.toml
  tests/e2e_csv/conf/diff_config.toml
  tests/ignore_generate_column/conf/diff_config.toml
  tests/rows/conf/diff_config.toml
  tests/rows_extreme_int/conf/diff_config.toml
Labels: status/LGT1, status/can-merge, size/L, needs-cherry-pick-release-5.0, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2

#386 tests: fix check diff
  tests/_utils/check_sync_diff
  tests/all_generate_column/conf/diff_config.toml
  tests/e2e/conf/diff_config.toml
  tests/e2e_csv/conf/diff_config.toml
  tests/ignore_generate_column/conf/diff_config.toml
  tests/rows/conf/diff_config.toml
  tests/rows_extreme_int/conf/diff_config.toml
Labels: status/LGT1, status/can-merge, size/S

#381 make version check more compatible
  v4/export/config.go
  v4/export/dump.go
  v4/export/sql.go
  v4/export/sql_test.go
Labels: status/LGT1, status/can-merge, size/M, cherry-pick-approved

#395 dumpling/gcs: fix http client credential problem
  v4/export/config.go
Labels: status/LGT1, status/can-merge, needs-cherry-pick-release-5.0, cherry-pick-approved, size/S, needs-cherry-pick-release-5.2
