Repository pingcap/dumpling, pull requests merged in 2021-04, with the labels that each got.

#257 dump: add split big tidb query to several small queries
  v4/export/dump.go
  v4/export/ir_impl.go
  v4/export/sql.go
  v4/export/sql_test.go
Labels: size/XL, status/LGT1, status/PTAL, status/can-merge

#264 [release-5.0] dump: add split big tidb query to several small queries
  v4/export/dump.go
  v4/export/ir_impl.go
  v4/export/sql.go
  v4/export/sql_test.go
Labels: cherry-pick-approved, size/XL, status/LGT1, status/can-merge

#265 Add conn session vars
  v4/export/sql.go
Labels: size/S, status/LGT1, status/can-merge

#262 sql: fix table sample sql generator bug
  go.mod
  go.sum
  v4/export/dump.go
  v4/export/dump_test.go
  v4/export/sql.go
  v4/export/sql_test.go
  v4/export/writer_util_test.go
Labels: size/L, status/LGT1, status/can-merge

#266 export: fix a metric not using labelNames
  v4/export/metrics.go
Labels: size/XS, status/LGT1, status/can-merge

#267 export: fix estimateTotalRowsCounter nil pointer
  v4/export/status.go
Labels: size/XS, status/LGT1, status/can-merge

#270 log: replace pingcap global logger when start dumpling binary
  v4/export/dump.go
  v4/export/writer_util_test.go
  v4/log/log.go
Labels: size/S, status/LGT1, status/PTAL, status/can-merge

#271 *: cherry-pick recent PRs for dumpling v5.0.1
  go.mod
  go.sum
  tests/basic/run.sh
  v4/export/dump.go
  v4/export/dump_test.go
  v4/export/metrics.go
  v4/export/sql.go
  v4/export/sql_test.go
  v4/export/status.go
  v4/export/writer_util_test.go
  v4/log/log.go
Labels: cherry-pick-approved, size/XL, status/LGT1, status/can-merge

#273 dump: always split TiDB v4.* tables through tidb rowid to save TiDB's memory
  tests/primary_key/data/pk_case_3.sql
  tests/primary_key/result/pk_case_3.sql
  v4/export/config.go
  v4/export/dump.go
  v4/export/sql.go
  v4/export/sql_test.go
  v4/export/sql_type.go
Labels: size/XXL, status/LGT1, status/PTAL, status/can-merge
